Esercizio 1
Crea un array numpy di 5x4 con vendite di 5 negozi per 4 prodotti. Calcola somma totale e media per ogni riga e colonna, poi applica uno sconto progressivo diverso per ciascun prodotto. Stampa i risultati.


In [8]:
import pandas as pd 
import numpy as np 

vendite = np.array(
    [[100, 125, 45, 89],
    [23, 45, 67, 34],
    [4, 5, 1, 3],
    [45, 56, 67, 78],
    [23, 34, 12, 45]], 
    dtype=float
)

somma_totale_riga = np.sum(vendite, axis = 1)
media_riga = np.mean(vendite, axis = 1)
somma_totale_colonna = np.sum(vendite, axis = 0)
media_colonna= np.mean(vendite, axis = 0)

sconti = np.array([0.05, 0.10, 0.15, 0.20, 0.30])

# Con .reshape(-1, 1) trasformi lo array monodimensionale in una colonna (5, 1)
# Questo permette a NumPy di moltiplicare ogni riga per il suo sconto specifico
sconti_matrice = sconti.reshape(-1,1) # -1 per automatizzare la grandezza della matrice
vendite_scontate = vendite * (1 - sconti_matrice)

print(f"Vendite non scontate: ", vendite)
print("\n")
print(f"Vendite scontate: ", vendite_scontate)
print("\n")

# oppure 

vendite_scontate = vendite.copy()

sconto_base = 0.10
incremento = 0.05
sconto_corrente = 0

print(f"Vendite non scontate: ", vendite)
print("\n")

for i, riga in enumerate(vendite):
    
    if sconto_corrente <= 0.50:
        sconto_corrente = sconto_base + (i * incremento)
        vendite_scontate[i] = riga * (1 - sconto_corrente)
    else:
        sconto_corrente = sconto_base
        vendite_scontate[i] = riga * (1 - sconto_corrente)
    print(f"sconto corrente: {np.round(sconto_corrente,2)}")

print(f"Vendite scontate: ", vendite_scontate)
print("\n")

# oppure 

vendite_scontate = vendite.copy()

# crea l'array degli sconti progressivi 
sconti = sconto_base + (np.arange(len(vendite)) * incremento)

# limita lo sconto massimo a 0.25 usando np.clip
sconti_limitati = np.clip(sconti, a_min=None, a_max=0.25).reshape(-1,1)

# applica gli sconti a tutta la matrice in un solo colpo
vendite_scontate = vendite * (1 - sconti_limitati)

print(f"Vendite non scontate: ", vendite)
print("\n")
print(f"Vendite scontate: ", vendite_scontate)
print("\n")


Vendite non scontate:  [[100. 125.  45.  89.]
 [ 23.  45.  67.  34.]
 [  4.   5.   1.   3.]
 [ 45.  56.  67.  78.]
 [ 23.  34.  12.  45.]]


Vendite scontate:  [[ 95.   118.75  42.75  84.55]
 [ 20.7   40.5   60.3   30.6 ]
 [  3.4    4.25   0.85   2.55]
 [ 36.    44.8   53.6   62.4 ]
 [ 16.1   23.8    8.4   31.5 ]]


Vendite non scontate:  [[100. 125.  45.  89.]
 [ 23.  45.  67.  34.]
 [  4.   5.   1.   3.]
 [ 45.  56.  67.  78.]
 [ 23.  34.  12.  45.]]


sconto corrente: 0.1
sconto corrente: 0.15
sconto corrente: 0.2
sconto corrente: 0.25
sconto corrente: 0.3
Vendite scontate:  [[ 90.   112.5   40.5   80.1 ]
 [ 19.55  38.25  56.95  28.9 ]
 [  3.2    4.     0.8    2.4 ]
 [ 33.75  42.    50.25  58.5 ]
 [ 16.1   23.8    8.4   31.5 ]]


Vendite non scontate:  [[100. 125.  45.  89.]
 [ 23.  45.  67.  34.]
 [  4.   5.   1.   3.]
 [ 45.  56.  67.  78.]
 [ 23.  34.  12.  45.]]


Vendite scontate:  [[ 90.   112.5   40.5   80.1 ]
 [ 19.55  38.25  56.95  28.9 ]
 [  3.2    4.     0.8    2.4 ]
 [ 3

Esercizio 2 
Crea un dizionario annidato con 3 utenti, ognuno con contatti, lista di acquisti e lista di categorie prodotti acquistati. Calcola totale acquisti, numero ordini e numero categorie distinte acquistate per utente. Stampa il risultato.


In [14]:
import numpy as np
import pandas as pd 

# dizionari utenti

utenti = {
    "utente_1":{"nome":"Anna","contatti":{"email":"anna@gmail.com"}, "acquisti":[100,200,50],"categorie_prod":["A","B","C"]},
    "utente_2":{"nome":"Luca","contatti":{"email":"luca@gmail.com"}, "acquisti":[12,34],"categorie_prod":["A","B"]},
    "utente_3":{"nome":"Paolo","contatti":{"email":"paolo@gmail.com"}, "acquisti":[100,200,300,100],"categorie_prod":["A","B","C","D"]},
}

print("Utenti iniziali:\n", utenti)

# Calcolo totale acquisti 
for user, info in utenti.items():

    lista_acquisti = info.get("acquisti",[])

    totale = sum(lista_acquisti)
    num_ordini = len(lista_acquisti)
    categorie_acquistate = len(set(info.get("categorie_prod",[])))

    print(f"{user} -> Totale: {totale} Euro | Ordini: {num_ordini} | Categorie uniche: {categorie_acquistate}")

Utenti iniziali:
 {'utente_1': {'nome': 'Anna', 'contatti': {'email': 'anna@gmail.com'}, 'acquisti': [100, 200, 50], 'categorie_prod': ['A', 'B', 'C']}, 'utente_2': {'nome': 'Luca', 'contatti': {'email': 'luca@gmail.com'}, 'acquisti': [12, 34], 'categorie_prod': ['A', 'B']}, 'utente_3': {'nome': 'Paolo', 'contatti': {'email': 'paolo@gmail.com'}, 'acquisti': [100, 200, 300, 100], 'categorie_prod': ['A', 'B', 'C', 'D']}}
utente_1 -> Totale: 350 Euro | Ordini: 3 | Categorie uniche: 3
utente_2 -> Totale: 46 Euro | Ordini: 2 | Categorie uniche: 2
utente_3 -> Totale: 700 Euro | Ordini: 4 | Categorie uniche: 4


Esercizio 3
Simula dati JSON annidati per 3 negozi, ciascun con 3 prodotti e vendite settimanali. Normalizza in DataFrame, calcola totale vendite per negozio e prodotto e media settimanale di vendite per prodotto. Stampa entrambi i DataFrame.


In [30]:
import pandas as pd 
import numpy as np

# JSON Negozi

import json

json_data = '''
[
  {
    "negozio": "Negozio Roma",
    "prodotti": [
      {"nome": "Computer Laptop", "vendite_settimanali": [12, 15, 10, 8, 20, 25, 18]},
      {"nome": "Smartphone", "vendite_settimanali": [25, 30, 22, 28, 35, 40, 32]},
      {"nome": "Cuffie Bluetooth", "vendite_settimanali": [8, 10, 12, 15, 18, 22, 14]}
    ]
  },
  {
    "negozio": "Negozio Milano",
    "prodotti": [
      {"nome": "Computer Laptop", "vendite_settimanali": [18, 20, 15, 19, 28, 30, 22]},
      {"nome": "Smartphone", "vendite_settimanali": [30, 35, 28, 32, 45, 50, 38]},
      {"nome": "Cuffie Bluetooth", "vendite_settimanali": [15, 12, 10, 14, 20, 25, 19]}
    ]
  },
  {
    "negozio": "Negozio Napoli",
    "prodotti": [
      {"nome": "Computer Laptop", "vendite_settimanali": [8, 10, 9, 11, 15, 18, 12]},
      {"nome": "Smartphone", "vendite_settimanali": [20, 22, 18, 25, 30, 33, 27]},
      {"nome": "Cuffie Bluetooth", "vendite_settimanali": [5, 7, 6, 9, 12, 15, 10]}
    ]
  }
]
'''

# conversione stringa json in oggetto python (lista di dizionari in questo caso)
data = json.loads(json_data)
print("Dati JSON:\n", data)

giorni = ["Lun","Mar","Mer","Gio","Ven","Sab","Dom"]
records=[] # memorizza i record del file Json

for negozio in data:
    for prodotto in negozio["prodotti"]:
        for i, vendita in enumerate(prodotto["vendite_settimanali"]): #indice numerico progressivo
            records.append({
                        "negozio": negozio["negozio"], 
                        "prodotto":prodotto["nome"], 
                        "giorno":giorni[i],
                        "vendita": vendita})

df = pd.DataFrame(records)
print(df.head())

# aggregazione vendite per negozio e prodotto
totali = df.groupby(["negozio","prodotto"])["vendita"].sum().reset_index()
media_settimanale_prodotto = df.groupby("prodotto")["vendita"].mean().reset_index()
media_settimanale_prodotto = media_settimanale_prodotto.rename(columns={"vendita":"media_vendite"})
media_settimanale_prodotto["media_vendite"] = np.round(media_settimanale_prodotto["media_vendite"],2)

print("\nVendite totali suddivise per negozio e prodotto:\n")
print(totali)
print("\nMedia settimanale suddivisa per prodotto:\n")
print(media_settimanale_prodotto)

Dati JSON:
 [{'negozio': 'Negozio Roma', 'prodotti': [{'nome': 'Computer Laptop', 'vendite_settimanali': [12, 15, 10, 8, 20, 25, 18]}, {'nome': 'Smartphone', 'vendite_settimanali': [25, 30, 22, 28, 35, 40, 32]}, {'nome': 'Cuffie Bluetooth', 'vendite_settimanali': [8, 10, 12, 15, 18, 22, 14]}]}, {'negozio': 'Negozio Milano', 'prodotti': [{'nome': 'Computer Laptop', 'vendite_settimanali': [18, 20, 15, 19, 28, 30, 22]}, {'nome': 'Smartphone', 'vendite_settimanali': [30, 35, 28, 32, 45, 50, 38]}, {'nome': 'Cuffie Bluetooth', 'vendite_settimanali': [15, 12, 10, 14, 20, 25, 19]}]}, {'negozio': 'Negozio Napoli', 'prodotti': [{'nome': 'Computer Laptop', 'vendite_settimanali': [8, 10, 9, 11, 15, 18, 12]}, {'nome': 'Smartphone', 'vendite_settimanali': [20, 22, 18, 25, 30, 33, 27]}, {'nome': 'Cuffie Bluetooth', 'vendite_settimanali': [5, 7, 6, 9, 12, 15, 10]}]}]
        negozio         prodotto giorno  vendita
0  Negozio Roma  Computer Laptop    Lun       12
1  Negozio Roma  Computer Laptop    Ma